fix: `KotlinNullnessAnnotation` warning (#829)
## 📜 Description

remove unnecessary @Nullable Annotation in kotlin
```log
Error: Do not use @Nullable in Kotlin; the nullability is already implied by the Kotlin type NativeModule? ending with ? [KotlinNullnessAnnotation]
  @Nullable
  ~~~~~~~~~

   Explanation for issues of type "KotlinNullnessAnnotation":
   In Kotlin, nullness is part of the type system; s: String is never null and
   s: String? is sometimes null, whether or not you add in additional
   annotations stating @NonNull or @Nullable. These are likely copy/paste
   mistakes, and are misleading.
```

## 💡 Motivation and Context

This problem will cause warning. Because warning as error, it will cause
build failed

## 📢 Changelog

### Android
remove unnecessary @Nullable annotation
KeyboardControllerPackage.getModule

## 🤔 How Has This Been Tested?

This commit not include any code logic change, so this is unlikely to be
a problem.

## 📝 Checklist

- [x] CI successfully passed
- [x] I added new mocks and corresponding unit-tests if library API was
changed