fix: access before initialization error (#1342)
## 📜 Description

Fixed error.

```sh
Metro error: Cannot access 'clampedScrollTarget' before initialization

  ReferenceError: Cannot access 'clampedScrollTarget' before initialization
```

## 💡 Motivation and Context

It seems like `export function` produces:

<img width="774" height="673" alt="image"
src="https://github.com/user-attachments/assets/6faf2e2d-de9c-4565-8adb-dba1c5cdc13d"
/>

While `export const` produces:

<img width="1000" height="663" alt="image"
src="https://github.com/user-attachments/assets/23cf8661-d418-4e55-8bf9-4314d591d732"
/>
...
<img width="1069" height="323" alt="image"
src="https://github.com/user-attachments/assets/ac30e296-7afc-4ec7-891f-bbe774ae6457"
/>

So with first case we try to export function that hasn't been declared
(though `function` should be hoisted?). Anyway across the package we
often use `arrow functions` and it doesn't cause issues, so let's
continue to use it.

In this PR I re-worked `helpers` file and used arrow functions instead
of regular functions.

## 📢 Changelog

<!-- High level overview of important changes -->
<!-- For example: fixed status bar manipulation; added new types
declarations; -->
<!-- If your changes don't affect one of platform/language below - then
remove this platform/language -->

### JS

- use `export const` instead of `export function`;
- use arrow functions in `helpers`;

## 🤔 How Has This Been Tested?

Tested in LegendList repo.

## 📸 Screenshots (if appropriate):

|Before|After|
|-------|-----|
|<img width="774" height="673" alt="image"
src="https://github.com/user-attachments/assets/6faf2e2d-de9c-4565-8adb-dba1c5cdc13d"
/>|<img width="1000" height="663" alt="image"
src="https://github.com/user-attachments/assets/23cf8661-d418-4e55-8bf9-4314d591d732"
/>|

## 📝 Checklist

- [x] CI successfully passed
- [x] I added new mocks and corresponding unit-tests if library API was
changed